version: '3.5'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=irtiza
      - POSTGRES_PASSWORD=password
      - POSTRGRES_DB=tododb
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - db:/var/lib/postgresql/data
  api:
    depends_on:
      - db
    restart: on-failure
    build: ./
    ports:
      - 5000:5000
    volumes:
      - .:/app/
  

volumes:
  db:
    driver: local